export enum MedioTransporte {
  MARITIMO = 'MARITIMO',
  TERRESTRE = 'TERRESTRE',
  AEREO = 'AEREO',
}

export enum AccionHistorial {
  COTIZACION_CREADA = 'COTIZACION_CREADA',
  TIMELINE_CONFIGURADO = 'TIMELINE_CONFIGURADO',
  PAIS_MODIFICADO = 'PAIS_MODIFICADO',
  TRANSPORTE_MODIFICADO = 'TRANSPORTE_MODIFICADO',
  DIAS_MODIFICADOS = 'DIAS_MODIFICADOS',
  PRODUCTO_APROBADO = 'PRODUCTO_APROBADO',
  PRODUCTO_DESAPROBADO = 'PRODUCTO_DESAPROBADO',
  COTIZACION_APROBADA_PARCIAL = 'COTIZACION_APROBADA_PARCIAL',
  COTIZACION_APROBADA_COMPLETA = 'COTIZACION_APROBADA_COMPLETA',
  SUPERVISOR_ASIGNADO = 'SUPERVISOR_ASIGNADO',
}